language: go

os:
- linux
- osx

go:
- 1.8

install:
- go get golang.org/x/sys/unix
- go get github.com/basalt79/GoLangRoulette/game
- go get github.com/basalt79/GoLangRoulette/game/gameType
- go get github.com/basalt79/GoLangRoulette/util
